import os
import subprocess

# ==========================================
# 1. USER CONFIGURATION
# ==========================================
# Output file name
FILENAME = "cascade_filter.cir"

# Number of cascaded stages
N_STAGES = 100  

# Component Values (Strings valid in SPICE)
# High-Pass Section (C1, R1)
C1_VAL = "560p"
R1_VAL = "18.94k"

# Low-Pass Section (R2, C2)
R2_VAL = "18.94k"
C2_VAL = "560p"

# ==========================================
# 2. NETLIST GENERATOR
# ==========================================

def create_netlist():
    spice_lines = []
    
    # Header
    spice_lines.append(f"* Automatic N-Stage Filter Generator (N={N_STAGES})")
    spice_lines.append("* Generated by Python")
    spice_lines.append("")

    # --- A. Subcircuit Definition ---
    # We define the stage ONCE using the variables above.
    # Topology: Input -> C1 -> (NodeMid) -> R2 -> Output
    #           (NodeMid) -> R1 -> GND
    #           Output    -> C2 -> GND
    spice_lines.append("* --- Single Stage Subcircuit ---")
    spice_lines.append(".subckt bp_stage in out gnd")
    spice_lines.append(f"  C1 in mid  {C1_VAL}")
    spice_lines.append(f"  R1 mid gnd {R1_VAL}")
    spice_lines.append(f"  R2 mid out {R2_VAL}")
    spice_lines.append(f"  C2 out gnd {C2_VAL}")
    spice_lines.append(".ends bp_stage")
    spice_lines.append("")

    # --- B. Main Circuit Components ---
    spice_lines.append("* --- Main Circuit ---")
    spice_lines.append("Vin source 0 AC 1")  # AC Source 1V

    # --- C. The Loop (Cascading Logic) ---
    # We define 'source' as the input to the first stage
    previous_node = "source"
    
    spice_lines.append(f"* Cascading {N_STAGES} stages automatically:")
    
    for i in range(1, N_STAGES + 1):
        # Determine output node name
        # If it's the last stage, name it 'v_out', otherwise 'n1', 'n2', etc.
        if i == N_STAGES:
            current_node = "v_out"
        else:
            current_node = f"n{i}"
            
        # Write the instance line (X1, X2, etc.)
        # Syntax: X<name> <in> <out> <gnd> <subckt_name>
        line = f"X{i} {previous_node} {current_node} 0 bp_stage"
        spice_lines.append(line)
        
        # Update previous_node for the next iteration
        previous_node = current_node

    spice_lines.append("")
    
    # --- D. Simulation Controls ---
    spice_lines.append("* --- Simulation Control ---")
    spice_lines.append(".control")
    # AC Analysis: Decade sweep, 10 points per decade, 1Hz to 100MHz
    spice_lines.append("  ac dec 20 1000 100000") 
    
    # Plotting: Input vs Output
    # We use 'db(v(node))' to see the magnitude in decibels
    spice_lines.append("  plot db(v(source)) db(v(v_out)) title 'Frequency Response'")
    spice_lines.append(".endc")
    spice_lines.append(".end")

    # Join lines and write to file
    netlist_content = "\n".join(spice_lines)
    
    with open(FILENAME, "w") as f:
        f.write(netlist_content)
    
    print(f"✅ Netlist successfully generated: {FILENAME}")
    return FILENAME

# ==========================================
# 3. EXECUTION
# ==========================================

if __name__ == "__main__":
    netlist_file = create_netlist()
    
    # Optional: Automatically run NGSpice if installed
    # Remove this block if you just want the text file.
    try:
        print("🚀 Attempting to run NGSpice...")
        subprocess.run(["ngspice", netlist_file], check=True)
    except FileNotFoundError:
        print("⚠️  NGSpice executable not found in PATH.")
        print(f"👉 Please open '{netlist_file}' manually in NGSpice.")
